### ISSUE TITLE
Add time-picker pattern to Form Controls page

### ISSUE THREAD

**Issue by scottmerker** [USPTO/designpatterns#128]
Source inspiration: http://jdewit.github.io/bootstrap-timepicker/

**Comment by epugh** [comment]
+1.  Used that time picker a lot.
> On May 4, 2016, at 1:09 PM, Scott Merker <notifications@github.com> wrote:
> 
> Source inspiration: http://jdewit.github.io/bootstrap-timepicker/ <http://jdewit.github.io/bootstrap-timepicker/>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/USPTO/designpatterns/issues/128>

-----------------------------------------------------
Eric Pugh | Principal | OpenSource Connections, LLC | 434.466.1467 | http://www.opensourceconnections.com <http://www.opensourceconnections.com/> | My Free/Busy <http://tinyurl.com/eric-cal>  
Co-Author: Apache Solr Enterprise Search Server, 3rd Ed <https://www.packtpub.com/big-data-and-business-intelligence/apache-solr-enterprise-search-server-third-edition-raw>	
This e-mail and all contents, including attachments, is considered to be Company Confidential unless explicitly stated otherwise, regardless of whether attachments are marked as such.

**Comment by scottmerker** [comment]
Time picker component added, will be rolled into 1.4.5 future version.
