### ISSUE TITLE
Build and documentation

### ISSUE THREAD

**Issue by ntunney** [USPTO/designpatterns#207]
Some things I couldn't find in the docs, such as what version of Bootstrap this includes?  It doesn't appear to be v4.0.0 since some of the classes I expect are missing.  In looking at the less files it wants a bootstrap/less directory, but LESS was dropped in favor of SASS in v4.

To use the templates provided, I had to grab CSS from the sample pages (not in the core dist/usptostrap.min.js) and pull in a bunch of inline CSS.  Is that by design?  An example I was following was https://uspto.github.io/designpatterns/1.x/docs/inspiration/master-detail-app.html

Can you please provide guidance?

Thanks,
Nic

**Comment by bmathews** [comment]
It's built on bootstrap v3.x at the moment.

Those "inspiration" templates have some one-off pieces of css that are specific to those demos that aren't part of the core css library. That is by design, yes. The purpose of those templates and that css is to show how you can glue the core patterns and components together. You're certainly free to use or adapt those resources as needed, but aren't intended to be production ready, reusable css like the the core css library.

Some of it is done through inline styles, some of it is using classes defined at the top of the demo html file, and some of the pages use shared styles from: https://github.com/USPTO/designpatterns/tree/gh-pages/front/styles/appDemo

**Comment by ntunney** [comment]
I will build with v3.  Thank you for your quick response and explanation.

Nic
