### ISSUE TITLE
Why sentence case for Button text?

### ISSUE THREAD

**Issue by JWKauffman** [USPTO/designpatterns#57]
I'm new here, so this may have been answered before. Why is our Button text sentence case when in my experience best practice dictates Title case? 

Thanks,
Jim Kauffman

**Comment by bmathews** [comment]
I don't think you'll find any _majority_ consensus on title case vs sentence case for buttons (at least we haven't). But, I think I would definitely argue that trends lately have been to sentence case everything and only capitalize proper nouns. 

Two pages I have open right now have sentence case buttons:

![image](https://cloud.githubusercontent.com/assets/848347/8525714/58271568-23b7-11e5-8a86-156f656d89fe.png)

![image](https://cloud.githubusercontent.com/assets/848347/8525746/7ea2b256-23b7-11e5-86eb-5d4035a3412c.png)

But a couple other pages I have open have title case. 

I've seen articles that have tried to make rules like "if it's more than two words use sentence case, otherwise use title case", but we've found it's easier to follow/remember "sentence case everything".

**Comment by arvalarva** [comment]
Also, the USPTO uses AP Style. Sentence case is more readable and readers tend to absorb the information and respond faster to sentence case.

Do you have any reference material supporting that best practice is to use title case? We’ve been researching this for menu items as well, so anything you have may help.

**Comment by JWKauffman** [comment]
The Microsoft Manual of Style and the OS X Human Factors Guidelines both specify title case. iOS Human Factors Guidelines specify title case. Android Style guide specifies ALL CAPS. I haven't run across any reference that recommends sentence case for buttons, although Nielsen/Norman recommends sentence case for command links. They don't mention button case.

**Comment by bmathews** [comment]
@JWKauffman These Windows guidelines show sentence case for buttons and every other UI element  besides titles:  https://msdn.microsoft.com/en-us/library/windows/desktop/dn742478.aspx

Android/Material guidelines specify all caps for buttons, but sentence case for everything else (like menu items/actions).

**Comment by JWKauffman** [comment]
You're quite right. Maybe they made this change for Win 8, it was title case for Win 7. I don't mind either way, but I'd never run across sentence case on a button before (although I now see that Github uses it). 

Thanks everyone.
