### ISSUE TITLE
Add baseline grid

### ISSUE THREAD

**Issue by AaronUXD** [USPTO/designpatterns#77]
Do we have this capability currently?
If not, I suggest we add in the future. I've noticed the lack of this "vertical rhythm" impacts both the effective grouping of UI elements and the aesthetics of many of our applications.

see article here:

https://scotch.io/tutorials/aesthetic-sass-3-typography-and-vertical-rhythm

**Comment by scottmerker** [comment]
Bootstrap has this defined in the less files. I think the problem lies when a PL user wants to position elements specifically and overrides the design already established. Hard to control that. Also not wrapping elements in the correct bootstrap containers has a huge effect on how elements are displayed when stacked vertically. 

Definitely something for consideration and further improvement.
